name: deploy-infrastructure

on:
  push:
    branches: [main]
    paths: ["/.deploy", ".github/workflows/infrastructure.yml"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
          enable-AzPSSession: true

      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Build ARM template using bicep
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: .deploy/main.bicep
          outputFilePath: ./azuredeploy.json

      # Deploy the ARM template
      - name: Deploy ARM template
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUB }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCEGROUP }}
          template: ./azuredeploy.json